[package]
name = "dechat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
arti-client = { version = "0.11.0", features = ["full"]}
libtor = "47.13.0"
rocket = "0.4.11"
serde = "1.0.192"
tokio = { version = "1.7", features = ["full"] }
tor-stream = "0.3.0"
